# Generated by Django 4.1.3 on 2022-11-26 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'coupon',
                    models.CharField(max_length=200, verbose_name='Купон'),
                ),
                (
                    'percent_off',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name='Скидка в процентах',
                    ),
                ),
                (
                    'amount_off',
                    models.PositiveIntegerField(
                        verbose_name='Скидка в валюте'
                    ),
                ),
                (
                    'duration',
                    models.CharField(
                        choices=[
                            ('forever', 'forever'),
                            ('once', 'once'),
                            ('repeating', 'repeating'),
                        ],
                        max_length=9,
                        verbose_name='Срок действия',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='orders.discount',
                verbose_name='Скидка',
            ),
        ),
    ]
