# Generated by Django 4.1.3 on 2022-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_discount_order_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.RemoveField(
            model_name='discount',
            name='amount_off',
        ),
        migrations.AlterField(
            model_name='discount',
            name='coupon',
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name='Купон'
            ),
        ),
    ]
