# Generated by Django 4.1.3 on 2022-11-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'orders',
            '0005_alter_discount_options_remove_discount_amount_off_and_more',
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='coupon',
            new_name='coupon_id',
        ),
    ]
