# Generated by Django 4.1.3 on 2022-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_coupon_discount_coupon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='coupon_id',
            field=models.CharField(
                blank=True,
                editable=False,
                help_text='Поле генерируется Stripe',
                max_length=200,
                null=True,
                verbose_name='Купон',
            ),
        ),
        migrations.AlterField(
            model_name='discount',
            name='duration',
            field=models.CharField(
                choices=[('Постоянно', 'forever'), ('Однократно', 'once')],
                max_length=11,
                verbose_name='Срок действия',
            ),
        ),
    ]
