# Generated by Django 4.1.3 on 2022-11-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_discount_coupon_id_alter_discount_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='duration',
            field=models.CharField(
                choices=[('forever', 'Постоянно'), ('once', 'Однократно')],
                max_length=11,
                verbose_name='Срок действия',
            ),
        ),
    ]
